
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/hexo-theme-melody.css

# scripts loaded in the end of the body
scripts:
- /js/hexo-theme-melody.js
